---
- hosts: host
  vars:
    - java_home: "/usr/local/jdk1.8.0_181"
    - zookeeper_hosts:
        - { 'host': "{{ groups['host'][0] }}", 'id': 1}
        - { 'host': "{{ groups['host'][1] }}", 'id': 2}
        - { 'host': "{{ groups['host'][2] }}", 'id': 3}
  roles:
  - { role: java, java_version: '1.8' }
  - { role: zookeeper }
