---

software_files_path: "/opt/software"
software_install_path: "/usr/local"

python_version: "2.7.10"

python_file: "Python-{{ python_version }}.tgz"
python_file_path: "{{ software_files_path }}/{{ python_file }}"
python_file_url: "http://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz"

change_pip_source: true
